### PR TITLE
Add error codes to return values

### PR DESCRIPTION
**Pull request by morganpdx**
Added error codes to all single-element error dictionaries.

Add error codes to multiple element error dictionaries (see access.py)
[errorlist.pdf](https://github.com/KSP-SpaceDock/SpaceDock-Backend/files/540537/errorlist.pdf)

### CODE REVIEW

**Comment by StollD** [comment]
Looks good to me so far

**Comment by StollD** [comment]
Given the recent changes on master, you might want to rebase your work on master.

**Comment by morganpdx** [comment]
Hey question @ThomasKerman - Do you want the same code applied to error messages that roughly mean the same, or if the message is different the code should be different?

i.e.: there's currently a different code for 
- `All fields are required`
- `Required data is missing`
- `Required fields are missing`

Similarly, there is already a code for `Missing username or password`, should I create a new one for `Password is required.`?

**Comment by StollD** [comment]
Using the same codes for simlar messages sounds good to me

**Comment by morganpdx** [comment]
okie...in that case I could use some help figuring out what would be considered similar messages.  :)  I think at this point, would you be ok with me just finishing up the code changes as they are and closing out this PR...then can create a new issue for consolidating error codes?

**Comment by morganpdx** [comment]
@ThomasKerman It took a while but...PR done!  😌

**Review by StollD — APPROVED** [review]

**Comment by StollD** [comment]
@morganpdx Since this PR is done, would you be interested in write access to the repository?

**Pull request merged**
